// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 21.4.2026, 15:06:39
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/morit/MyCode/moritzfieler.com/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/moritzfieler.com/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/moritzfieler.com/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/moritzfieler.com/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/morit/MyCode/moritzfieler.com/frontend/composables/**/*.{js,ts,mjs}","C:/Users/morit/MyCode/moritzfieler.com/frontend/utils/**/*.{js,ts,mjs}","C:/Users/morit/MyCode/moritzfieler.com/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/moritzfieler.com/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/moritzfieler.com/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/morit/MyCode/moritzfieler.com/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;