<script setup lang="ts">
import {
  HomeIcon,
  BriefcaseIcon,
  SparklesIcon,
  EnvelopeIcon,
  SunIcon,
  MoonIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  XMarkIcon,
  PhotoIcon,
  StarIcon,
  ArrowsPointingOutIcon,
  ArrowsPointingInIcon,
  PencilSquareIcon,
  CodeBracketIcon,
  CircleStackIcon,
  Battery50Icon,
  BoltIcon,
  PhoneIcon,
  MapPinIcon,
  CalendarDaysIcon,
  DevicePhoneMobileIcon,
  SwatchIcon,
  ArrowsRightLeftIcon,
  UsersIcon,
  ArrowPathIcon,
  ShieldCheckIcon,
  MapIcon,
  TrophyIcon,
  ClockIcon,
  SpeakerWaveIcon,
  Battery100Icon,
  FireIcon,
  WifiIcon,
  ChartBarIcon,
  Squares2X2Icon,
  LightBulbIcon,
  PuzzlePieceIcon,
  BookOpenIcon,
  PaintBrushIcon,
  SwatchIcon as WatchIcon,
} from '@heroicons/vue/24/solid'

interface Props {
  name: string
  size?: 'sm' | 'md' | 'lg' | 'xl'
}

withDefaults(defineProps<Props>(), {
  size: 'md',
})

const sizeMap = {
  sm: 'w-4 h-4',
  md: 'w-5 h-5',
  lg: 'w-6 h-6',
  xl: 'w-8 h-8',
}

const iconMap: Record<string, any> = {
  House: HomeIcon,
  Home: HomeIcon,
  Sun: SunIcon,
  Moon: MoonIcon,
  Briefcase: BriefcaseIcon,
  Work: BriefcaseIcon,
  MagicWand: SparklesIcon,
  Sparkles: SparklesIcon,
  Skills: SparklesIcon,
  EnvelopeSimple: EnvelopeIcon,
  Envelope: EnvelopeIcon,
  Mail: EnvelopeIcon,
  ArrowDown: ChevronDownIcon,
  ChevronDown: ChevronDownIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronRight: ChevronRightIcon,
  CaretLeft: ChevronLeftIcon,
  CaretRight: ChevronRightIcon,
  ArrowLeft: ArrowLeftIcon,
  ArrowRight: ArrowRightIcon,
  X: XMarkIcon,
  XMark: XMarkIcon,
  Close: XMarkIcon,
  Photo: PhotoIcon,
  Image: PhotoIcon,
  Star: StarIcon,
  Expand: ArrowsPointingOutIcon,
  ArrowsPointingOut: ArrowsPointingOutIcon,
  Collapse: ArrowsPointingInIcon,
  ArrowsPointingIn: ArrowsPointingInIcon,
  PenNib: PencilSquareIcon,
  Design: PencilSquareIcon,
  Code: CodeBracketIcon,
  Database: CircleStackIcon,
  BatteryCharging: Battery50Icon,
  Plug: BoltIcon,
  Lightning: BoltIcon,
  Bolt: BoltIcon,
  Phone: PhoneIcon,
  MapPin: MapPinIcon,
  Location: MapPinIcon,
  CalendarDays: CalendarDaysIcon,
  DevicePhoneMobile: DevicePhoneMobileIcon,
  Swatch: SwatchIcon,
  ArrowsRightLeft: ArrowsRightLeftIcon,
  Users: UsersIcon,
  ArrowPath: ArrowPathIcon,
  ShieldCheck: ShieldCheckIcon,
  Map: MapIcon,
  Trophy: TrophyIcon,
  Clock: ClockIcon,
  SpeakerWave: SpeakerWaveIcon,
  Battery100: Battery100Icon,
  Fire: FireIcon,
  Wifi: WifiIcon,
  ChartBar: ChartBarIcon,
  Squares2x2: Squares2X2Icon,
  LightBulb: LightBulbIcon,
  PuzzlePiece: PuzzlePieceIcon,
  BookOpen: BookOpenIcon,
  PaintBrush: PaintBrushIcon,
  Watch: WatchIcon,
}
</script>

<template>
  <Component
    :is="iconMap[name] || HomeIcon"
    :class="sizeMap[size]"
  />
</template>
